import Vue from "vue";

// 按需引入vant-UI框架方法（https://youzan.github.io/vant/#/zh-CN/intro）
import { Tab, Tabs } from "vant";
// 引用引用字体css 不加此句则从网络拉取字体文件
import "vant/lib/icon/local.css";
Vue.use(Tab).use(Tabs);
import { Row, Col } from "vant";
Vue.use(Row).use(Col);
import { Image } from "vant";
Vue.use(Image);
import { List } from "vant";
Vue.use(List);
import { Cell, CellGroup } from "vant";
Vue.use(Cell).use(CellGroup);
import { Icon } from "vant";
Vue.use(Icon);
import { Grid, GridItem } from "vant";
Vue.use(Grid).use(GridItem);
import { Switch } from "vant";
Vue.use(Switch);
import { NavBar } from "vant";
Vue.use(NavBar);
import { Divider } from "vant";
Vue.use(Divider);
import { Popup } from "vant";
Vue.use(Popup);
import { Button } from "vant";
Vue.use(Button);
import { Swipe, SwipeItem } from "vant";
Vue.use(Swipe).use(SwipeItem);
import { Toast } from "vant";
Toast.setDefaultOptions("loading", { forbidClick: true });
Vue.use(Toast);
import { Lazyload } from "vant";
Vue.use(Lazyload);
import { Field } from "vant";
Vue.use(Field);
import { ActionSheet } from "vant";
Vue.use(ActionSheet);
import { PullRefresh } from "vant";
Vue.use(PullRefresh);
import { Slider } from "vant";
Vue.use(Slider);
import { Loading } from "vant";
Vue.use(Loading);
import { Sticky } from "vant";
Vue.use(Sticky);
import { Uploader } from "vant";
Vue.use(Uploader);
import { Panel } from "vant";
Vue.use(Panel);
import { Picker } from "vant";
Vue.use(Picker);
import { Overlay } from "vant";
Vue.use(Overlay);
import { Search } from "vant";
Vue.use(Search);
import { DropdownMenu, DropdownItem } from "vant";
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
import { NoticeBar } from "vant";
Vue.use(NoticeBar);
import { Dialog } from "vant";
Vue.use(Dialog);
import { SwipeCell } from "vant";
Vue.use(SwipeCell);
import { Notify } from "vant";
Vue.use(Notify);
