import Vue from 'vue';
import menu from './menu.vue';
import search from './search.vue';
import more from './more.vue';
import close from './close.vue';
import arrow from './arrow.vue';
import nodata from './nodata.vue';
import iconReturn from './return.vue';
import warn from './warn.vue';
import error from './error.vue';
import success from './success.vue';
import loading from './loading.vue';
import plus from './plus.vue';
import reduce from './reduce.vue';
import help from './help.vue';
import signout from './signout.vue';
import user from './user.vue';
import EyeClose from './eye-close.vue';
import EyeOpen from './eye-open.vue';
import PwEyeOpen from './pw-eye-open.vue';
import PwEyeClose from './pw-eye-close.vue';
import iconHome from './icon-home.vue';
import iconTrade from './icon-trade.vue';
import iconLegal from './icon-legal.vue';
import iconFinance from './icon-finance.vue';
import iconInfo from './icon-info.vue';

Vue.component('icon-menu', menu);
Vue.component('icon-search', search);
Vue.component('icon-more', more);
Vue.component('icon-close', close);
Vue.component('icon-arrow', arrow);
Vue.component('icon-nodata', nodata);
Vue.component('icon-return', iconReturn);
Vue.component('icon-warn', warn);
Vue.component('icon-error', error);
Vue.component('icon-success', success);
Vue.component('icon-loading', loading);
Vue.component('icon-plus', plus);
Vue.component('icon-reduce', reduce);
Vue.component('icon-help', help);
Vue.component('icon-signout', signout);
Vue.component('icon-user', user);
Vue.component('icon-eye-close', EyeClose);
Vue.component('icon-eye-open', EyeOpen);
Vue.component('icon-pw-eye-open', PwEyeOpen);
Vue.component('icon-pw-eye-close', PwEyeClose);
Vue.component('icon-home', iconHome);
Vue.component('icon-trade', iconTrade);
Vue.component('icon-legal', iconLegal);
Vue.component('icon-finance', iconFinance);
Vue.component('icon-info', iconInfo);
